### ISSUE TITLE
Cant make grid work

### ISSUE THREAD

**Issue by filiptrifunovic-mile** [silvia-odwyer/lightbox.js#49]
Hi,

First of all thank you for making such a great tool.
I have a small problem, by default SlideshowLightbox comes with classes grid-cols-3.
So for my project i wanted it to make in 2 rows, where first row would be occupied by one picture and 2nd row would contain all the rest of pictures.(heres the picture of it https://github.com/silvia-odwyer/lightbox.js/assets/114927397/ee401a33-ada0-4975-a9bc-f545aff5217b).

But whatever i do i cant make it work, when i set grid-rows-2 it just make more than 2 rows, i dont no if need some other classes or theres something in component thats doing that.

Thank you.

**Comment by silvia-odwyer** [comment]
@filiptrifunovic-mile Hi Filip,
Certainly, this type of layout could be created using CSS Flexbox, and I've created some example markup and CSS to showcase how to create this layout below:

JSX
```jsx
<SlideshowLightbox
  lightboxIdentifier="lbox1"
  showThumbnails={true}>
  <div className="imgs">

    <img src={"https://images.pexels.com/photos/13425910/pexels-photo-13425910.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}
    alt="Forest with blue sky and clouds"
    data-lightboxjs="lbox1" />

    <div className="thumbnails">
      <img src={"https://images.pexels.com/photos/4275885/pexels-photo-4275885.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}
        alt="Mountain range with wood cabin in green field" data-lightboxjs="lbox1" />
      <img src={"https://images.pexels.com/photos/13208323/pexels-photo-13208323.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}
        alt="Blue lake and mountain range" data-lightboxjs="lbox1" />
      <img src={"https://images.pexels.com/photos/13996896/pexels-photo-13996896.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2"}
         alt="Mountain range with blue sky in the foreground" data-lightboxjs="lbox1" />
    </div>

  </div>
</SlideshowLightbox>
```

CSS
```css

.imgs img {
  width: 100%;
  border-radius: 4px;
}

.imgs {
  width: 60vw;
  height: 80vh;
  display: flex;
  flex-direction: row;
  margin-bottom: 10vh;
  margin-top: 10vh;
  margin-left: 10vh;

}

.thumbnails {
  width: 60vw;
  display: flex;
  flex-direction: row;
  height: 10vh;
  gap: 8px;
  margin-top: 10px;
}

.thumbnails img {
  height: 12vw;
  object-fit: cover;

}
```

Here is what it looks like:

![image](https://github.com/silvia-odwyer/lightbox.js/assets/32362757/e1343480-f2a2-4e9c-81b4-a942e73bef45)

If you're using Next.js, then the configuration of the lightbox is slightly different, and the guide for this is [here](https://www.getlightboxjs.com/docs/NextJsGuide/).

Hopefully that helps, and let me know if you have any questions or queries.
